INFO     root:conftest.py:211 === Starting api_response_conditions_negative_400 Test (Negative) ===
INFO     root:conftest.py:212 API Response: 400 | {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-3d744861425da2543a10ffc4733e4811-cb7986df7e7dd7bf-00","errors":{"Id":["'Id' must not be empty."]}}
INFO     root:conftest.py:221 Test 'api_response_conditions_negative_400' (Negative) SUCCESS.
INFO     root:conftest.py:222 === Ending api_response_conditions_negative_400 Test (Negative) ===