INFO     root:conftest.py:184 === Starting auth_token Test ===
INFO     root:conftest.py:185 API Response: 200 | {"kind":"identitytoolkit#VerifyCustomTokenResponse","idToken":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjNhM2JkODk4ZGE1MGE4OWViOWUxY2YwYjdhN2VmZTM1OTNkNDEwNjgiLCJ0eXAiOiJKV1QifQ.eyJhZ3JlZW1lbnRzU2lnbmVkIjpmYWxzZSwiZW1haWxWZXJpZmllZCI6dHJ1ZSwibWVtYmVyQmlydGhEYXRlIjoiMDMvMDgvMTk5MSAwMDowMDowMCIsIm1lbWJlcklkIjozODI5LCJtZW1iZXJGaXJzdE5hbWUiOiJRQSIsIm1lbWJlckxhc3ROYW1lIjoiTmVyZCIsIm1lbWJlckRpc3BsYXlOYW1lIjoiTmVyZENvcmUtUUEiLCJtZW1iZXJOYW1lIjoiTmVyZCBDb3JlIiwibWVtYmVyTnVtYmVyIjoiMDAzODI5IiwibWVtYmVyUGhvbmUiOiIrMTMxMDU1NTU1NTUiLCJtZW1iZXJUaW1lWm9uZSI6IiswNzowMCIsInBlcm1pc3Npb25zIjpbXSwicm9sZXMiOltdLCJ1c2VySWQiOiI2NDJlZWZhNjc1ZGU3MDdjNDRhZmM4NDAiLCJvcHRJblNoYXJlTmFtZSI6ZmFsc2UsImF1dGhlbnRpY2F0b3JFbmFibGVkIjpmYWxzZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvcmUtZGV2LTliNTRiIiwiYXVkIjoiY29yZS1kZXYtOWI1NGIiLCJhdXRoX3RpbWUiOjE3MDE5MzI3MjUsInVzZXJfaWQiOiJvQ0RSbHNNOVMzWjdiejBXNzMyYlBUcWlGUUgzIiwic3ViIjoib0NEUmxzTTlTM1o3YnowVzczMmJQVHFpRlFIMyIsImlhdCI6MTcwMTkzMjcyNSwiZXhwIjoxNzAxOTM2MzI1LCJlbWFpbCI6Im5lcmRjb3JlX3FhdGVhbSsxQG5lcmR1bml0ZWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibmVyZGNvcmVfcWF0ZWFtKzFAbmVyZHVuaXRlZC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJjdXN0b20ifX0.F5eMSuxWX7Ny3u4nAMxzPcXl8ejy08HvaBaqFZ571jVfEQkSBlTql4-yks0qVPS14Dml9gfzKrbRWMMKP2UI688jRepgGgLNkvVs-89tunBGhlFWF5a4GTE_n9riQE_7rjd1KOG_7kzWE4gK6iNhyuePeAF5igBqiD0CMqQ_yeMMtBI4vGleYFSvSL6z_Bx2JSC3izQ1UqYYRzW2_ZJwVCm-SHQLk0m-LrLjSPkwiNTe9AfxzqsEMSRb_jqC7g5hiZ2L0cy3FRWtqmXTrVHWwJuYP5Sj4shpNfdsAWUTuRlESzs0Xu2QGk_0_c0XAZXUUg11tA1tJ6WtVN0ydneNlQ","refreshToken":"AMf-vBwecM1ihV4fsj0VJGdWWJJ3YvoR4ZKISO4rYh1LFOiFYUszMHY6pgpQtLVu5v0ry6lCsDMNRYCf11Rz_5pXYTZLxc1T-9uFQpNRxctGIVdMICsjOaqqP_0fkgrWacZvyIQSrC__8nV0RayhwqSiC_e6fF6MCdeTSz9j9zVvNReydOXXEXq2Sqs2FR0CXvwKizKv9TLXu-acSmX2CWO1WlTkJI24jOHPfLv7s4x_HgNQ8MGtZPMKnJ9vt_Kcy3VGyw6tmbmU5asMjDIoVB0gGwcWMe0EWLwffyO7fYphRRc3sRMNaOZmhGIU7IS2OyUknMKdgeiSHalqFc1dEdi0ATSSlozT6BexEQSRkZsmbmrgazuK51ARMGBq3Nzbe5ATM6h4moqYhaHqO2JJ5fOdq7ShUNNDidunyMHo8Yjl8RAiSbiEEkIHlDUBezCtjrbQiC_CErSOT0aLKo1vvVMuQ4r0wTj0-0-57l6h6cxfhEdZl_t3mKaFAyKIkfN09LFzLkLvTBb5DBXm3je2gieX0m3tOFc0_njyoVLR9yqzBmTWn7Y_mg4tJT1WUcqlXEYO1f3za4mVX8ekx2Sq3V8yLusbdq96JNzmyf0K5zACOLW58vE2UGuww_O7Sp65fOaa2M8l1CgdesPxfwkqHr2ONsO-iBeMEAKVqWA0EyehKzGNJ46z4hJA5kB4DHjnmVAQTgNw6_snPrfzjKANwa4N3NDM4xfOEg","expiresIn":"3600","isNewUser":false}
INFO     root:conftest.py:195 Test 'auth_token' SUCCESS.
INFO     root:conftest.py:196 === Ending auth_token Test ===
INFO     root:conftest.py:184 === Starting test_get_a_role Test ===
INFO     root:conftest.py:185 API Response: 401 | 
INFO     root:conftest.py:191 Test 'test_get_a_role' FAILED.
ERROR    root:conftest.py:192 API response status code: 401
assert 401 in [200, 201, 202, 203, 204, 205]
 +  where 401 = <Response [401]>.status_code
Traceback (most recent call last):
  File "/home/runner/work/qa-nerd-core-backend/qa-nerd-core-backend/conftest.py", line 189, in api_response_conditions
    assert response.status_code in allowed_status_codes, f"API response status code: {response.status_code}"
AssertionError: API response status code: 401
assert 401 in [200, 201, 202, 203, 204, 205]
 +  where 401 = <Response [401]>.status_code